services:
  nerva:
    build: .
    container_name: nerva
    user: "1000:1000"
    restart: unless-stopped

    ports:
      - "17566:17566"   # RPC ONLY

    volumes:
      - ${APP_DATA_DIR}/data/nerva:/root/.nerva
