services:
  nervad:
    user: "1000:1000"
    restart: unless-stopped
    command: --p2p-bind-ip=0.0.0.0 --p2p-bind-port=17565 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=17566 --non-interactive --confirm-external-bind --data-dir=/data/nerva --log-level 0
    image: sn1f3rt/nerva:latest@sha256:888417ae11481476ecde6b38a45b8300fe9c8e21d053c72f0d4e903b7282c7a2
    ports:
      - "17565:17565"
      - "17566:17566"
    volumes:
      - ${APP_DATA_DIR}/data/nerva:/data/nerva

  web:
    image: nginx:alpine
    container_name: ${APP_ID}_web
    restart: unless-stopped
    ports:
      - "17578:80"
    volumes:
      - ${APP_DATA_DIR}/app:/usr/share/nginx/html:ro
    depends_on:
      - nervad