version: "3.7"

services:
  nerva:
    build: .
    container_name: nerva_node
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "17566:17566"
    volumes:
      - nerva_data:/root/.nerva

volumes:
  nerva_data:["/start.sh"]
